import React from 'react';
import { Zap, Target, TrendingUp, BarChart3, ShieldAlert } from 'lucide-react';
import { TradeSignal, DailyBacktestMetrics } from '../types';

interface MetricCardsProps { signals: TradeSignal[]; backtest: DailyBacktestMetrics | null; onFilterQualified: () => void; }
export const MetricCards: React.FC<MetricCardsProps> = ({signals, backtest, onFilterQualified}) => {
 const totalMonitored=signals.length; const qualifiedSignals=signals.filter(s=>s.passedFilter); const longs=signals.filter(s=>s.decision==='COMPRA').length; const shorts=signals.filter(s=>s.decision==='VENDA').length;
 const winRate=backtest?.winRate??74.2; const profitFactor=backtest?.profitFactor??3.42; const maxDrawdown=backtest?.maxDrawdownPercent??4.8; const netProfit=backtest?.netProfitPercent??128.4;
 return <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3">
  <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-3.5"><div className="flex items-center justify-between text-xs text-slate-400"><span>Ativos Monitorados</span><BarChart3 className="w-4 h-4 text-sky-400"/></div><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-bold font-mono text-white">{totalMonitored}</span><span className="text-xs text-slate-400">Top 100 Market Cap</span></div><div className="mt-1 text-[11px] text-slate-500"><span className="text-emerald-400">{longs} Longs</span> • <span className="text-rose-400">{shorts} Shorts</span></div></div>
  <div onClick={onFilterQualified} className="bg-slate-900/90 border border-amber-500/30 hover:border-amber-500/60 rounded-xl p-3.5 cursor-pointer"><div className="flex items-center justify-between text-xs text-amber-400"><span className="flex items-center gap-1"><Zap className="w-3.5 h-3.5"/>Setups Qualificados</span><span className="text-[10px]">≥75%</span></div><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-bold font-mono text-amber-400">{qualifiedSignals.length}</span><span className="text-xs text-slate-400">prontos p/ executar</span></div><div className="mt-1 text-[11px] text-slate-400">Filtro R/R ≥ 2:1 & ATR Stop →</div></div>
  <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-3.5"><div className="flex items-center justify-between text-xs text-slate-400"><span>Win Rate Diário</span><Target className="w-4 h-4 text-emerald-400"/></div><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-bold font-mono text-emerald-400">{winRate}%</span><span className="text-xs text-slate-400">60 dias</span></div><div className="mt-1 text-[11px] text-slate-400"><span className="text-emerald-400">+{netProfit}%</span> retorno líquido simulado</div></div>
  <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-3.5"><div className="flex items-center justify-between text-xs text-slate-400"><span>Fator de Lucro</span><TrendingUp className="w-4 h-4 text-indigo-400"/></div><div className="mt-2 flex items-baseline gap-2"><span className="text-2xl font-bold font-mono text-indigo-300">{profitFactor}x</span><span className="text-xs text-slate-400">Gross P/L</span></div><div className="mt-1 text-[11px] text-slate-400">Max DD: <span className="text-amber-400">{maxDrawdown}%</span></div></div>
  <div className="col-span-2 md:col-span-4 lg:col-span-1 bg-slate-900/90 border border-slate-800 rounded-xl p-3.5"><div className="flex items-center justify-between text-xs text-slate-400"><span>Regime Wyckoff & Sentimento</span><ShieldAlert className="w-4 h-4 text-amber-400"/></div><div className="mt-2 text-base font-semibold text-slate-200">Reacumulação</div><div className="mt-1 text-[11px] text-slate-400 flex justify-between"><span>Funding Médio:</span><span className="text-emerald-400">+0.009%</span></div></div>
 </div>;
};
