import React,{useEffect,useState}from'react';
import{ShieldCheck,Calculator,AlertTriangle}from'lucide-react';

type Props={symbol:string;side:'LONG'|'SHORT'|'WAIT'|'NEUTRO';entry:number;stop:number;tp1:number;tp2:number;tp3:number;score:number;quality:string};
type Risk={allowed:boolean;status:string;reason?:string;riskPercent:number;account?:{equity:number;riskBudget:number;maxPositionPercent:number;maxNotional:number};trade?:{entry:number;stop:number;stopDistance:number;stopPercent:number;quantity:number;notional:number;lossAtStop:number};targets?:{name:string;price:number;rr:number}[];averageRR?:number};
export function RiskEnginePanel({symbol,side,entry,stop,tp1,tp2,tp3,score,quality}:Props){
 const[data,setData]=useState<Risk|null>(null);const[loading,setLoading]=useState(false);const[equity,setEquity]=useState(1000);const[riskPercent,setRiskPercent]=useState(.5);
 const run=async()=>{setLoading(true);try{const r=await fetch('/api/risk-engine',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbol,side,entry,stop,tp1,tp2,tp3,score,quality,equity,riskPercent,maxPositionPercent:25})});setData(await r.json())}finally{setLoading(false)}};
 useEffect(()=>{run()},[symbol,side,entry,stop,tp1,tp2,tp3,score,quality,equity,riskPercent]);
 return <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-bold flex gap-2"><ShieldCheck size={17}/>Risk Engine Profissional</h3><span className={`text-xs font-bold ${data?.allowed?'text-emerald-400':'text-amber-400'}`}>{loading?'calculando...':data?.status}</span></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-2"><label className="bg-slate-950 rounded-lg p-3"><div className="text-[10px] text-slate-500">CAPITAL</div><input className="bg-transparent w-full font-mono" type="number" min="1" value={equity} onChange={e=>setEquity(Number(e.target.value))}/></label><label className="bg-slate-950 rounded-lg p-3"><div className="text-[10px] text-slate-500">RISCO / TRADE</div><input className="bg-transparent w-full font-mono" type="number" min="0.1" max="2" step="0.1" value={riskPercent} onChange={e=>setRiskPercent(Number(e.target.value))}/><span className="text-[10px] text-slate-500">%</span></label><div className="bg-slate-950 rounded-lg p-3"><div className="text-[10px] text-slate-500">PERDA NO SL</div><b className="font-mono">${data?.trade?.lossAtStop?.toFixed(2)||'--'}</b></div><div className="bg-slate-950 rounded-lg p-3"><div className="text-[10px] text-slate-500">R/R MÉDIO</div><b className="font-mono">{data?.averageRR?.toFixed(2)||'--'}</b></div></div>
 {data?.trade&&<div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[['Entrada',data.trade.entry],['Stop',data.trade.stop],['Qtd.',data.trade.quantity],['Notional',`$${data.trade.notional.toFixed(2)}`],['Dist. SL',`${data.trade.stopPercent.toFixed(2)}%`]].map(([k,v])=><div className="bg-slate-950 rounded-lg p-3" key={String(k)}><div className="text-[10px] text-slate-500">{k}</div><b className="font-mono">{typeof v==='number'?v.toLocaleString('en-US',{maximumFractionDigits:8}):v}</b></div>)}</div>}
 {data?.targets&&<div className="flex flex-wrap gap-2">{data.targets.map(t=><span key={t.name} className="text-xs bg-slate-950 border border-slate-800 rounded px-3 py-2">{t.name}: <b>{t.price}</b> • {t.rr}R</span>)}</div>}
 {!data?.allowed&&<div className="text-xs text-amber-400 flex gap-2"><AlertTriangle size={14}/>{data?.reason||'Trade bloqueado pelo filtro de risco/confluência.'}</div>}
 <div className="text-[10px] text-slate-500 flex gap-2"><Calculator size={12}/>Limites conservadores: risco máximo 2%, posição máxima 25%, R/R mínimo 1.5 e stop máximo 3%.</div></div>
}
