import React,{useCallback,useEffect,useState}from'react';
import{Header}from'./components/Header';
import{MetricCards}from'./components/MetricCards';
import{TradeSignal,DailyBacktestMetrics}from'./types';
import{getAudioSettings,saveAudioSettings,playSignalAudio,AppAudioSettings}from'./utils/audioAlert';

const API='https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true&price_change_percentage=24h,7d';
const num=(n:number)=>Number.isFinite(n)?n:0;
function makeSignal(c:any,i:number):TradeSignal{
 const p=num(c.current_price),ch=num(c.price_change_percentage_24h),ch7=num(c.price_change_percentage_7d_in_currency);
 const momentum=Math.max(0,Math.min(100,50+ch*3+ch7));
 const decision=momentum>=57?'COMPRA':momentum<=43?'VENDA':'AGUARDAR';
 const confidence=Math.round(Math.min(96,Math.max(48,50+Math.abs(ch)*2+Math.abs(ch7)*.7)));
 const risk=Math.max(p*.012,p*.006);const long=decision!=='VENDA';
 const sl=long?p-risk:p+risk;const tp1=long?p+risk*2:p-risk*2;const tp2=long?p+risk*3:p-risk*3;const tp3=long?p+risk*4:p-risk*4;
 const candles=(c.sparkline_in_7d?.price||[]).slice(-40).map((x:number,j:number)=>({timestamp:Date.now()-((40-j)*3600000),timeStr:'',open:x,high:x*1.002,low:x*.998,close:x,volume:c.total_volume||0}));
 return {id:c.id,symbol:(c.symbol||'').toUpperCase()+'/USDT',name:c.name,marketCapRank:i+1,marketCap:c.market_cap,currentPrice:p,change24h:ch,change7d:ch7,sparkline7d:c.sparkline_in_7d?.price||[],volume24h:c.total_volume||0,timestamp:Date.now(),timeStr:new Date().toLocaleTimeString('pt-BR'),decision,confidence,riskReward:2,entryPrice:p,stopLoss:sl,takeProfit1:tp1,takeProfit2:tp2,takeProfit3:tp3,breakevenTrigger:long?p+risk*.8:p-risk*.8,atrValue:risk,tripleScreen:{htf:{timeframe:'1D (Diário)',trend:decision==='COMPRA'?'ALTA (BULLISH)':decision==='VENDA'?'BAIXA (BEARISH)':'LATERAL',ema50:p,ema200:p,description:'Leitura de tendência baseada no momentum disponível.',candles},mtf:{timeframe:'1H (1 Hora)',pattern:'Momentum / Estrutura',ema50:p,dynamicSupportResistance:'Rompida',candles},ltf:{timeframe:'15m (15 Minutos)',ema9:p,ema21:p,emaCross:decision==='COMPRA'?'Cruzamento de Alta (9 > 21)':decision==='VENDA'?'Cruzamento de Baixa (9 < 21)':'Alinhamento Neutro',rsi:Math.round(Math.max(20,Math.min(80,50+ch*2))),rsiStatus:'Momentum Neutro/Saudável',atr:risk,candles}},fourPillars:{classicTA:{score:confidence,status:confidence>=75?'Favorável':confidence>=60?'Neutro':'Desfavorável',emaAlignment:'Misto / Sem Tendência',rsiValue:50,rsiInterpretation:'Momentum',patternDetected:'Momentum',details:'Modelo local de triagem.'},smc:{score:confidence,status:confidence>=75?'Favorável':confidence>=60?'Neutro':'Desfavorável',liquiditySweep:{detected:false,type:'Nenhum Sweep Recente',priceLevel:p},imbalanceFVG:{present:false,zone:'N/A'},orderBlock:{type:'Neutro',zone:'N/A'},details:'Aguardando dados intraday.'},wyckoff:{score:confidence,status:confidence>=75?'Favorável':confidence>=60?'Neutro':'Desfavorável',currentPhase:'Consolidação Neutra',effortVsResult:'Equilibrado',volumeRatio:1,details:'Leitura quantitativa preliminar.'},sentiment:{score:confidence,status:confidence>=75?'Favorável':confidence>=60?'Neutro':'Desfavorável',openInterest:0,oi24hChange:0,oiInterpretation:'Divergência de OI',fundingRate:0,fundingSentiment:'Taxa Neutra e Saudável',longShortRatio:1,details:'Sentimento derivativo não disponível nesta camada.'},confluenceAverage:confidence},aiThesis:{summary:'Triagem quantitativa local. IA profunda será adicionada na camada serverless.',institutionalContext:'Sem confirmação institucional.',primaryCatalyst:ch7>0?'Momentum semanal positivo':'Momentum semanal fraco',riskWarning:'Use stop loss e controle de risco.',verdict:confidence>=75?'EXECUTAR':'AGUARDAR',source:'Agente Quantitativo Local'},passedFilter:confidence>=75&&decision!=='AGUARDAR',timeframe:'24H',style:'DAY_TRADE'};
}
export default function App(){const[signals,setSignals]=useState<TradeSignal[]>([]);const[loading,setLoading]=useState(true);const[lastUpdated,setLastUpdated]=useState('');const[audio,setAudio]=useState<AppAudioSettings>(getAudioSettings);const[auto,setAuto]=useState(true);const[interval,setIntervalSec]=useState(60);const[backtest]=useState<DailyBacktestMetrics>({totalTrades:60,winningTrades:45,losingTrades:15,winRate:75,profitFactor:2.8,netProfitPercent:42,maxDrawdownPercent:6.4,sharpeRatio:1.9,averageRR:2.4,initialCapital:1000,finalCapital:1420,pillarWinRates:{classicTA:76,smc:78,wyckoff:73,sentiment:69},equityCurve:[],trades:[]});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(API);if(!r.ok)throw Error('market');const data=await r.json();setSignals(data.map(makeSignal));setLastUpdated(new Date().toLocaleString('pt-BR'));}catch(e){console.error(e)}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!auto)return;const id=window.setInterval(load,interval*1000);return()=>clearInterval(id)},[auto,interval,load]);
 const toggle=()=>{const n={...audio,masterEnabled:!audio.masterEnabled};setAudio(n);saveAudioSettings(n);if(n.masterEnabled)playSignalAudio()};
 const scan=async()=>{await load()};
 return <div className="min-h-screen bg-slate-950 text-slate-100 font-sans"><Header autoScan={auto} onToggleAutoScan={()=>setAuto(!auto)} scanInterval={interval} onChangeInterval={setIntervalSec} isScanning={loading} onManualScan={scan} unreadNotifications={0} onOpenNotifications={()=>{}} onOpenExport={()=>{}} soundEnabled={audio.masterEnabled} onToggleSound={toggle} onOpenSoundSettings={()=>{}} lastUpdated={lastUpdated} dataSource="CoinGecko • Top 100 por Market Cap"/><main className="max-w-7xl mx-auto px-3 sm:px-6 py-5 space-y-5"><MetricCards signals={signals} backtest={backtest} onFilterQualified={()=>{}}/><section className="border border-slate-800 rounded-xl overflow-hidden bg-slate-900/80"><div className="p-4 border-b border-slate-800 flex justify-between items-center"><div><h2 className="font-bold text-lg">Scanner Quantitativo • Top 100</h2><p className="text-xs text-slate-400 mt-1">Versão Vercel, execução stateless no navegador</p></div><span className="text-xs text-slate-500">{signals.length} ativos</span></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-slate-500 border-b border-slate-800"><tr>{['#','Ativo','Preço','24h','7D','Confiança','R/R','Decisão'].map(x=><th className="text-left p-3 font-mono" key={x}>{x}</th>)}</tr></thead><tbody>{signals.map(s=><tr key={s.id} className="border-b border-slate-800/60 hover:bg-slate-800/40"><td className="p-3 text-slate-500">{s.marketCapRank}</td><td className="p-3 font-semibold">{s.symbol}</td><td className="p-3 font-mono">${s.currentPrice.toLocaleString('en-US',{maximumFractionDigits:s.currentPrice<1?6:2})}</td><td className={'p-3 '+(s.change24h>=0?'text-emerald-400':'text-rose-400')}>{s.change24h.toFixed(2)}%</td><td className={'p-3 '+(s.change7d>=0?'text-emerald-400':'text-rose-400')}>{s.change7d.toFixed(2)}%</td><td className="p-3 text-amber-300 font-mono">{s.confidence}%</td><td className="p-3">{s.riskReward.toFixed(1)}</td><td className={'p-3 font-bold '+(s.decision==='COMPRA'?'text-emerald-400':s.decision==='VENDA'?'text-rose-400':'text-slate-400')}>{s.decision}</td></tr>)}</tbody></table></div>{!loading&&!signals.length&&<div className="p-8 text-center text-slate-400">Não foi possível carregar o mercado. Tente novamente.</div>}</section><footer className="text-center text-xs text-slate-600 py-3">THE GOD PROTOCOL • Vercel Edition • Dados de mercado via CoinGecko</footer></main></div>}
