import { callGroq, parseJson } from './_lib/groq.js';

type AgentName='TECHNICAL'|'SMC'|'WYCKOFF_GANN'|'DIVERGENCE';
type Decision='LONG'|'SHORT'|'NEUTRO';
type AgentResult={agent:AgentName;decision:Decision;confidence:number;thesis:string;keyLevels:string[];invalidation:string;riskFlags:string[];model?:string;error?:string};

const AGENTS:Array<{name:AgentName;mission:string}>=[
{name:'TECHNICAL',mission:'Avalie Triple Screen, tendência, estrutura, EMA 9/21/50/200, RSI, MACD se disponível, ATR, volume, momentum, suportes, resistências, rompimentos e retestes. Exija alinhamento 4H/1H/15M.'},
{name:'SMC',mission:'Avalie BOS, CHoCH, swing highs/lows, BSL, SSL, sweeps, displacement, FVG, Order Blocks, mitigation e premium/discount. Procure liquidez -> deslocamento -> estrutura -> retorno à zona.'},
{name:'WYCKOFF_GANN',mission:'Avalie acumulação, distribuição, markup, markdown, spring, test, SOS, LPS, UTAD, SOW, esforço/resultado e absorção. Só use Gann se preço/tempo/ciclos forem objetivamente sustentados.'},
{name:'DIVERGENCE',mission:'Avalie divergências bullish/bearish regulares ou ocultas entre preço e RSI/MACD/momentum/volume quando fornecidos. Compare pivôs equivalentes e diferencie potencial de confirmação.'}
];

function compactMarket(m:any){
 const pick=(x:any,keys:string[])=>{const o:any={};if(!x||typeof x!=='object')return o;for(const k of keys)if(x[k]!==undefined)o[k]=x[k];return o};
 const frames=(x:any)=>{if(!x||typeof x!=='object')return undefined;const o:any={};for(const [k,v] of Object.entries(x)){o[k]=pick(v as any,['close','ema9','ema21','ema50','ema200','rsi','atr','volumeRatio','confluence','trend','bos','bias','score','divergence','sweep','premiumDiscount','structure']);}return o};
 return {symbol:m?.symbol,current:pick(m?.current,['symbol','currentPrice','change24h','volume24h','fourPillars','squeezeBreakout']),setup:pick(m?.setup,['side','score','confluence','entry','stop','tp1','tp2','tp3','riskReward','timeframe','confirmations','invalidations']),technical:{confluence:m?.technical?.confluence,timeframes:frames(m?.technical?.timeframes)},smc:{timeframes:frames(m?.smc?.timeframes)}};
}

function promptFor(agent:typeof AGENTS[number],symbol:string,market:any){return `ATIVO ${symbol}. Você é o especialista ${agent.name}. ${agent.mission}\nUse somente os dados abaixo. Não invente evidências. Se faltar dado, declare desconhecido. Não autorize execução. Responda somente JSON: {"decision":"LONG|SHORT|NEUTRO","confidence":0-100,"thesis":"curta","keyLevels":["níveis observáveis"],"invalidation":"condição objetiva","riskFlags":["riscos concretos"]}.\nDADOS:\n${JSON.stringify(compactMarket(market))}`;}

function normalizeAgent(p:any){const decision:Decision=p?.decision==='LONG'||p?.decision==='SHORT'?p.decision:'NEUTRO';return{decision,confidence:Math.max(0,Math.min(100,Number(p?.confidence)||0)),thesis:String(p?.thesis||''),keyLevels:Array.isArray(p?.keyLevels)?p.keyLevels.map(String).slice(0,5):[],invalidation:String(p?.invalidation||''),riskFlags:Array.isArray(p?.riskFlags)?p.riskFlags.map(String).slice(0,5):[]};}

async function runAgent(agent:typeof AGENTS[number],symbol:string,market:any):Promise<AgentResult>{try{const model=process.env[`GROQ_MODEL_${agent.name}`]||process.env.GROQ_MODEL||'openai/gpt-oss-20b';const result=await callGroq([{role:'system',content:'Analista quantitativo conservador. Nunca invente evidências.'},{role:'user',content:promptFor(agent,symbol,market)}],{model,temperature:.1,maxTokens:220});return{agent:agent.name,...normalizeAgent(parseJson<any>(result.content)),model:result.model};}catch(error){return{agent:agent.name,decision:'NEUTRO',confidence:0,thesis:'Agente indisponível nesta rodada.',keyLevels:[],invalidation:'Sem validação.',riskFlags:[error instanceof Error?error.message:'Erro desconhecido'],error:'AGENT_UNAVAILABLE'};}}

async function runAgentsWithLimit(symbol:string,market:any){const results:AgentResult[]=[];for(let i=0;i<AGENTS.length;i+=2){const batch=AGENTS.slice(i,i+2);results.push(...await Promise.all(batch.map(a=>runAgent(a,symbol,market))));}return results;}
function numeric(v:any){const n=Number(v);return Number.isFinite(n)?n:null;}
function directional(v:any){const t=String(v||'').toUpperCase();return t.includes('BULL')||t.includes('LONG')||t.includes('BUY')||t.includes('ALTA')?1:t.includes('BEAR')||t.includes('SHORT')||t.includes('SELL')||t.includes('BAIXA')?-1:0;}
function masterScore(results:AgentResult[],market:any){const valid=results.filter(r=>!r.error&&r.confidence>0&&(r.decision==='LONG'||r.decision==='SHORT'));const agentRaw=valid.reduce((s,r)=>s+(r.decision==='LONG'?r.confidence:-r.confidence),0),directionalAgentScore=valid.length?agentRaw/valid.length:0;const setup=market?.setup,setupSide=setup?.side as Decision|undefined,setupScore=numeric(setup?.score)||0,setupContribution=setupSide==='LONG'?Math.min(20,setupScore/5):setupSide==='SHORT'?-Math.min(20,setupScore/5):0;const pillars=market?.current?.fourPillars,pv=pillars?[pillars.classicTA?.score,pillars.smc?.score,pillars.wyckoff?.score,pillars.sentiment?.score].map(numeric).filter((x:any):x is number=>x!==null):[],pillarAverage=pv.length?pv.reduce((a:number,b:number)=>a+b,0)/pv.length:50,pillarBias=Math.max(-15,Math.min(15,pillarAverage-50));const technicalBias=directional(market?.technical?.confluence),frames=market?.smc?.timeframes?Object.values(market.smc.timeframes) as any[]:[],sb=frames.map(x=>directional(x?.bias)).filter(Boolean),smcBias=sb.length?sb.reduce((a,b)=>a+b,0)/sb.length:0,objectiveBonus=Math.max(-10,Math.min(10,technicalBias*5+smcBias*5));const raw=directionalAgentScore*.65+setupContribution+pillarBias+objectiveBonus,score=Math.round(Math.max(0,Math.min(100,Math.abs(raw)))),decision:Decision=valid.length>=3&&raw>=35?'LONG':valid.length>=3&&raw<=-35?'SHORT':'NEUTRO',aligned=valid.filter(r=>r.decision===decision).length,agreement=valid.length>=3&&decision!=='NEUTRO'?Math.round(aligned/valid.length*100):0,quality=valid.length<3?'DADOS_INSUFICIENTES':score>=70&&agreement>=75?'A+':score>=50&&agreement>=60?'A':score>=35&&agreement>=50?'B':'C',trigger=decision==='NEUTRO'?'AGUARDAR CONFLUÊNCIA':agreement>=75&&score>=60?'AGUARDAR GATILHO':'AGUARDAR CONFIRMAÇÃO',confidence=valid.length>=3?Math.min(100,Math.round(score*.8+agreement*.2)):0;return{score,decision,confidence,agreement,quality,trigger,components:{agentScore:Math.round(directionalAgentScore),setupContribution:Math.round(setupContribution),pillarBias:Math.round(pillarBias),objectiveBonus:Math.round(objectiveBonus)}};}

export async function POST(req:Request){try{const body=await req.json().catch(()=>({})),symbol=String(body?.symbol||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''),market=body?.market;if(!market)return new Response(JSON.stringify({error:'Envie market.'}),{status:400,headers:{'content-type':'application/json'}});const results=await runAgentsWithLimit(symbol,market),master=masterScore(results,market);return new Response(JSON.stringify({symbol,timestamp:Date.now(),mode:'AI_ANALYSIS_ONLY',provider:'GROQ',agents:results,supervisor:{...master,agentsUsed:results.filter(r=>!r.error&&r.confidence>0).length,status:master.quality==='DADOS_INSUFICIENTES'?'DADOS_INSUFICIENTES':'CONFLUENCIA_MESTRE',executionAllowed:false,note:'Os especialistas analisam dados objetivos. O Supervisor exige 3+ agentes válidos, consenso e validação independente do Risk Engine. Execução real permanece bloqueada.'}}),{headers:{'content-type':'application/json','cache-control':'no-store'}});}catch(error){return new Response(JSON.stringify({error:error instanceof Error?error.message:'Falha no orquestrador'}),{status:500,headers:{'content-type':'application/json'}});}}
