import {loadPaperStore,savePaperStore} from './_lib/paper-persistence.js';
type Position={id:string;symbol:string;side:'LONG'|'SHORT';entry:number;quantity:number;notional:number;stop:number;tp1:number;tp2:number;tp3:number;openedAt:number;status:'OPEN'|'CLOSED';exit?:number;closedAt?:number;realizedPnl?:number;closeReason?:string};
type Store={equity:number;startingEquity:number;positions:Position[];trades:Position[];updatedAt:number;peakEquity:number;maxDrawdown:number};
const g=globalThis as typeof globalThis & {_paperStore?:Store;_paperStorePromise?:Promise<Store>};
const fresh=():Store=>({equity:1000,startingEquity:1000,positions:[],trades:[],updatedAt:Date.now(),peakEquity:1000,maxDrawdown:0});
async function store(){if(g._paperStore)return g._paperStore;if(!g._paperStorePromise)g._paperStorePromise=(async()=>{const loaded=await loadPaperStore();const s=(loaded||fresh()) as Store;g._paperStore=s;return s})();return g._paperStorePromise}
async function persist(s:Store){s.updatedAt=Date.now();await savePaperStore(s)}
function n(v:unknown,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function json(x:unknown,status=200){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
function stats(s:Store){const t=s.trades;const wins=t.filter(x=>n(x.realizedPnl)>0),losses=t.filter(x=>n(x.realizedPnl)<0);const grossProfit=wins.reduce((a,x)=>a+n(x.realizedPnl),0),grossLoss=Math.abs(losses.reduce((a,x)=>a+n(x.realizedPnl),0));const winRate=t.length?wins.length/t.length*100:0;const profitFactor=grossLoss?grossProfit/grossLoss:wins.length?Infinity:0;const avgPnl=t.length?(s.equity-s.startingEquity)/t.length:0;const avgR=t.length?t.reduce((a,x)=>{const risk=Math.abs(x.entry-x.stop)*x.quantity;return a+(risk?n(x.realizedPnl)/risk:0)},0)/t.length:0;let peak=s.startingEquity,dd=0;for(let i=0;i<t.length;i++){const eq=s.startingEquity+t.slice(0,i+1).reduce((a,y)=>a+n(y.realizedPnl),0);peak=Math.max(peak,eq);dd=Math.max(dd,peak?((peak-eq)/peak)*100:0)}const bySide=(side:'LONG'|'SHORT')=>{const q=t.filter(x=>x.side===side);return {trades:q.length,pnl:q.reduce((a,x)=>a+n(x.realizedPnl),0),winRate:q.length?q.filter(x=>n(x.realizedPnl)>0).length/q.length*100:0}};const best=t.reduce((a,x)=>n(x.realizedPnl)>n(a?.realizedPnl,-Infinity)?x:a,null as Position|null);const worst=t.reduce((a,x)=>n(x.realizedPnl)<n(a?.realizedPnl,Infinity)?x:a,null as Position|null);let streak=0,streakType='';for(let i=t.length-1;i>=0;i--){const type=n(t[i].realizedPnl)>0?'W':n(t[i].realizedPnl)<0?'L':'E';if(!streakType)streakType=type;if(type!==streakType)break;streak++}return {totalTrades:t.length,wins:wins.length,losses:losses.length,winRate,grossProfit,grossLoss,profitFactor:profitFactor===Infinity?null:profitFactor,avgPnl,avgR,bestTrade:best?{pnl:n(best.realizedPnl),symbol:best.symbol,side:best.side}:null,worstTrade:worst?{pnl:n(worst.realizedPnl),symbol:worst.symbol,side:worst.side}:null,streak:{type:streakType,count:streak},maxDrawdown:Math.max(s.maxDrawdown,dd),maxDrawdownUsd:Math.max(0,Math.max(s.startingEquity,s.peakEquity)-s.equity),bySide:{LONG:bySide('LONG'),SHORT:bySide('SHORT')}}}
function touch(s:Store){s.peakEquity=Math.max(s.peakEquity,s.equity);const dd=s.peakEquity?((s.peakEquity-s.equity)/s.peakEquity)*100:0;s.maxDrawdown=Math.max(s.maxDrawdown,dd);s.updatedAt=Date.now()}
async function priceFor(symbol:string){const clean=encodeURIComponent(symbol.toUpperCase().replace(/[^A-Z0-9]/g,''));for(const url of [`https://fapi.binance.com/fapi/v1/ticker/price?symbol=${clean}`,`https://api.binance.com/api/v3/ticker/price?symbol=${clean}`]){try{const r=await fetch(url,{signal:AbortSignal.timeout(5000)});if(r.ok){const d=await r.json() as any;const p=n(d?.price);if(p>0)return p}}catch{}}return 0}
function closePosition(s:Store,p:Position,exit:number,reason:string){const pnl=(p.side==='LONG'?exit-p.entry:p.entry-exit)*p.quantity;p.status='CLOSED';p.exit=exit;p.closedAt=Date.now();p.realizedPnl=pnl;p.closeReason=reason;s.equity+=pnl;s.trades.push({...p});s.positions=s.positions.filter(x=>x.id!==p.id)}
export async function GET(){const s=await store();touch(s);return json({mode:'PAPER_TRADING',enabled:true,persistence:persistenceEnabled(),equity:s.equity,startingEquity:s.startingEquity,pnl:s.equity-s.startingEquity,openPositions:s.positions.filter(p=>p.status==='OPEN'),closedTrades:s.trades,stats:stats(s),updatedAt:s.updatedAt})}
export async function POST(req:Request){const b=await req.json().catch(()=>({})) as any;const s=await store();const action=String(b.action||'').toUpperCase();
 if(action==='RESET'){s.equity=n(b.equity,1000);s.startingEquity=s.equity;s.positions=[];s.trades=[];s.updatedAt=Date.now();s.peakEquity=s.equity;s.maxDrawdown=0;await persist(s);return json({ok:true,mode:'PAPER_TRADING',equity:s.equity,stats:stats(s)})}
 if(action==='OPEN'){const side=b.side==='SHORT'?'SHORT':'LONG',entry=n(b.entry),qty=n(b.quantity),stop=n(b.stop),tp1=n(b.tp1),tp2=n(b.tp2),tp3=n(b.tp3);if(!b.symbol||entry<=0||qty<=0||stop<=0)return json({error:'symbol, entry, quantity e stop são obrigatórios'},400);if(s.positions.length>=3)return json({error:'limite de 3 posições abertas atingido'},409);const p:Position={id:`P-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,symbol:String(b.symbol),side,entry,quantity:qty,notional:entry*qty,stop,tp1,tp2,tp3,openedAt:Date.now(),status:'OPEN'};s.positions.push(p);touch(s);await persist(s);return json({ok:true,position:p,mode:'PAPER_TRADING',persistence:persistenceEnabled()})}
 if(action==='CLOSE'){const id=String(b.id||'');const p=s.positions.find(x=>x.id===id&&x.status==='OPEN');if(!p)return json({error:'posição aberta não encontrada'},404);const exit=n(b.exit);if(exit<=0)return json({error:'exit inválido'},400);closePosition(s,p,exit,String(b.reason||'MANUAL'));touch(s);await persist(s);return json({ok:true,trade:s.trades.at(-1),equity:s.equity,pnl:s.equity-s.startingEquity,stats:stats(s),mode:'PAPER_TRADING'})}
 if(action==='MARK'){const prices=b.prices||{};const closed:Position[]=[];const open=[...s.positions];for(const p of open){if(p.status!=='OPEN')continue;let price=n(prices[p.symbol]);if(price<=0)price=await priceFor(p.symbol);if(price<=0)continue;let reason='';if(p.side==='LONG'){if(price<=p.stop)reason='STOP';else if(p.tp3>0&&price>=p.tp3)reason='TP3'}else{if(price>=p.stop)reason='STOP';else if(p.tp3>0&&price<=p.tp3)reason='TP3'}if(reason){closePosition(s,p,price,reason);closed.push(s.trades.at(-1)!)}}touch(s);await persist(s);return json({ok:true,closed,equity:s.equity,pnl:s.equity-s.startingEquity,openPositions:s.positions,stats:stats(s),mode:'PAPER_TRADING',persistence:persistenceEnabled(),updatedAt:s.updatedAt})}
 return json({error:'action deve ser OPEN, CLOSE, MARK ou RESET'},400)}
