type Bar={t:number;o:number;h:number;l:number;c:number;v:number};
const BINANCE='https://fapi.binance.com/fapi/v1/klines';
const ema=(x:number[],p:number)=>{if(!x.length)return 0;const k=2/(p+1);let e=x[0];for(let i=1;i<x.length;i++)e=x[i]*k+e*(1-k);return e};
const rsi=(x:number[],p=14)=>{if(x.length<=p)return 50;let g=0,l=0;for(let i=x.length-p;i<x.length;i++){const d=x[i]-x[i-1];if(d>=0)g+=d;else l-=d}return l===0?100:100-100/(1+g/l)};
const atr=(b:Bar[],p=14)=>{if(b.length<p+1)return 0;let s=0;for(let i=b.length-p;i<b.length;i++)s+=Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c));return s/p};
const structure=(b:Bar[])=>{const n=b.length;if(n<8)return{trend:'NEUTRO',bos:'NENHUM',swingHigh:0,swingLow:0};const hi=Math.max(...b.slice(n-8,n-2).map(x=>x.h)),lo=Math.min(...b.slice(n-8,n-2).map(x=>x.l)),last=b[n-1],prev=b[n-2];return{trend:last.c>prev.c?'ALTA':last.c<prev.c?'BAIXA':'NEUTRO',bos:last.c>hi?'BOS_ALTA':last.c<lo?'BOS_BAIXA':'NENHUM',swingHigh:hi,swingLow:lo}};
const divergence=(b:Bar[])=>{const n=b.length;if(n<40)return'NENHUMA';const p=b.map(x=>x.c),rs=p.map((_,i)=>rsi(p.slice(0,i+1))),p1=p[n-20],p2=p[n-1],r1=rs[n-20],r2=rs[n-1];return p2<p1&&r2>r1+3?'BULLISH':p2>p1&&r2<r1-3?'BEARISH':'NENHUMA'};
const analyze=(b:Bar[])=>{const c=b.map(x=>x.c),e9=ema(c,9),e21=ema(c,21),e50=ema(c,50),e200=ema(c,200),r=rsi(c),a=atr(b),s=structure(b),avgV=b.slice(-20).reduce((x,y)=>x+y.v,0)/Math.min(20,b.length);return{close:c.at(-1),ema9:e9,ema21:e21,ema50:e50,ema200:e200,rsi:r,atr:a,structure:s,divergence:divergence(b),volumeRatio:b.at(-1)!.v/Math.max(avgV,1)}};
async function candles(symbol:string,interval:string):Promise<Bar[]>{const r=await fetch(`${BINANCE}?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=250`,{headers:{accept:'application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Binance ${interval}: ${r.status}`);return(await r.json() as any[]).map(x=>({t:Number(x[0]),o:Number(x[1]),h:Number(x[2]),l:Number(x[3]),c:Number(x[4]),v:Number(x[5])}))};
export async function GET(req:Request){const u=new URL(req.url,'https://bottrade-vercel.local');const symbol=(u.searchParams.get('symbol')||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,'');try{const rows=await Promise.all(['3m','5m','15m','1h','4h','1d'].map(async i=>[i,analyze(await candles(symbol,i))] as const));const timeframes=Object.fromEntries(rows),x=[timeframes['15m'],timeframes['1h'],timeframes['1d']],bull=x.filter(v=>v.structure.trend==='ALTA').length,bear=x.filter(v=>v.structure.trend==='BAIXA').length;return new Response(JSON.stringify({symbol,timeframes,confluence:bull>=2?'ALTA':bear>=2?'BAIXA':'NEUTRO',source:'Binance USDⓈ-M Futures',timestamp:Date.now()}),{headers:{'content-type':'application/json','cache-control':'s-maxage=10, stale-while-revalidate=20'}})}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:'Technical data unavailable'}),{status:502,headers:{'content-type':'application/json'}})}}