type Bar = { t:number; o:number; h:number; l:number; c:number; v:number };

const BINANCE='https://fapi.binance.com/fapi/v1/klines';

function ema(xs:number[],p:number){ if(!xs.length)return 0; const k=2/(p+1); let e=xs[0]; for(let i=1;i<xs.length;i++) e=xs[i]*k+e*(1-k); return e; }
function rsi(xs:number[],p=14){ if(xs.length<=p)return 50; let g=0,l=0; for(let i=xs.length-p;i<xs.length;i++){const d=xs[i]-xs[i-1]; if(d>=0)g+=d;else l-=d;} return l===0?100:100-100/(1+g/l); }
function atr(b:Bar[],p=14){ if(b.length<p+1)return 0; let s=0; for(let i=b.length-p;i<b.length;i++)s+=Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c)); return s/p; }
function structure(b:Bar[]){ const n=b.length; if(n<8)return {trend:'NEUTRO',bos:'NENHUM',swingHigh:0,swingLow:0}; const hi=Math.max(...b.slice(n-8,n-2).map(x=>x.h)), lo=Math.min(...b.slice(n-8,n-2).map(x=>x.l)); const last=b[n-1]; const prev=b[n-2]; const bos=last.c>hi?'BOS_ALTA':last.c<lo?'BOS_BAIXA':'NENHUM'; const trend=last.c>prev.c?'ALTA':last.c<prev.c?'BAIXA':'NEUTRO'; return {trend,bos,swingHigh:hi,swingLow:lo}; }
function divergence(b:Bar[]){ const n=b.length; if(n<40)return 'NENHUMA'; const prices=b.map(x=>x.c), rs=prices.map((_,i)=>rsi(prices.slice(0,i+1))); const p1=prices[n-20],p2=prices[n-1],r1=rs[n-20],r2=rs[n-1]; if(p2<p1&&r2>r1+3)return 'BULLISH'; if(p2>p1&&r2<r1-3)return 'BEARISH'; return 'NENHUMA'; }
function analyze(b:Bar[]){ const c=b.map(x=>x.c); const e9=ema(c,9),e21=ema(c,21),e50=ema(c,50),e200=ema(c,200); const r=rsi(c), a=atr(b); const s=structure(b); const avgV=b.slice(-20).reduce((x,y)=>x+y.v,0)/Math.min(20,b.length); const vol=b[b.length-1].v/Math.max(avgV,1); return {close:c[c.length-1],ema9:e9,ema21:e21,ema50:e50,ema200:e200,rsi:r,atr:a,structure:s,divergence:divergence(b),volumeRatio:vol}; }
async function candles(symbol:string,interval:string,limit=250):Promise<Bar[]>{ const r=await fetch(`${BINANCE}?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=${limit}`,{headers:{accept:'application/json'}}); if(!r.ok)throw new Error(`Binance ${interval}: ${r.status}`); const raw=await r.json() as unknown[]; return raw.map((x:any)=>({t:Number(x[0]),o:Number(x[1]),h:Number(x[2]),l:Number(x[3]),c:Number(x[4]),v:Number(x[5])})); }

export default async function handler(req:Request){ if(req.method!=='GET')return new Response(JSON.stringify({error:'Method not allowed'}),{status:405,headers:{'content-type':'application/json'}}); const u=new URL(req.url); const symbol=(u.searchParams.get('symbol')||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''); const intervals=['3m','5m','15m','1h','4h','1d']; try{ const rows=await Promise.all(intervals.map(async i=>{const b=await candles(symbol,i);return [i,analyze(b)] as const;})); const timeframes=Object.fromEntries(rows); const l=timeframes['15m'],m=timeframes['1h'],h=timeframes['1d']; const bull=[l,m,h].filter(x=>x.structure.trend==='ALTA').length; const bear=[l,m,h].filter(x=>x.structure.trend==='BAIXA').length; const confluence=bull>=2?'ALTA':bear>=2?'BAIXA':'NEUTRO'; return new Response(JSON.stringify({symbol,timeframes,confluence,source:'Binance USDⓈ-M Futures',timestamp:Date.now()}),{headers:{'content-type':'application/json','cache-control':'s-maxage=10, stale-while-revalidate=20'}}); }catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:'Technical data unavailable'}),{status:502,headers:{'content-type':'application/json'}});} }
